version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_DATABASE: wakizashi
      MONGO_REPLICA_SET_NAME: rs0
    networks:
      - wakizashi-dev
    volumes:
      - mongodb:/data
    ports:
      - "27017:27017"
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate().ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
    command: "--bind_ip_all --replSet rs0"

  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${mq_pass}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - wakizashi-dev
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  wakizashi-dev:

volumes:
  rabbitmq:
  mongodb: